version: '3.8'

services:
  mysql:
    container_name: 'civic-mysql'
    build:
        context: .
        dockerfile: Dockerfile
        target: mysql
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    environment:
      MYSQL_DATABASE: 'civicappdatabase'
      MYSQL_PASSWORD: '332003'
      MYSQL_ROOT_PASSWORD: '332003'
      MYSQL_USER: 'root1'
    ports:
      - '3306:3306'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  rabbitmq:
    container_name: 'civic-rabbitmq'
    build:
      context: .
      dockerfile: Dockerfile
      target: rabbitmq
    environment:
      - 'RABBITMQ_DEFAULT_USER=guest'
      - 'RABBITMQ_DEFAULT_PASS=guest'
      - 'RABBITMQ_STOMP_ENABLED=true'
    ports:
      - '5672:5672'
      - '15672:15672'
      - '61613:61613'
      - '15674:15674'
    restart: unless-stopped
  redis:
    container_name: 'civic-redis'
    build:
      context: .
      dockerfile: Dockerfile
      target: redis
    ports:
      - '6379:6379'
    restart: unless-stopped
  spring-app:
    container_name: 'spring-app'
    build:
      context: .
      dockerfile: Dockerfile
      target: springapp
    ports:
      - '8081:8081'
    environment:
      SPRING_RABBITMQ_HOST: 'civic-rabbitmq'
    depends_on:
      - rabbitmq
      - mysql
      - redis
    restart: unless-stopped

